theme: jekyll-theme-slate
title: AIST – Advanced Information Systems and Technology
description: The research group “AIST – Advanced Information Systems and Technology” researches software solutions in the fields of eHealth, Machine Learning and Data Mining as well as Computer Vision.
